Info2: <<
Package: testtools-py%type_pkg[python]
Version: 0.9.34
Revision: 1
Type: python (2.6 2.7 3.1 3.2 3.3)
Description: Extensions to Python unit testing framework
Maintainer: Daniel Johnson <daniel@daniel-johnson.org>
License: BSD
Homepage: http://pypi.python.org/pypi/testtools

Source: https://pypi.python.org/packages/source/t/testtools/testtools-%v.tar.gz
Source-MD5: 51d37e7376a70cee40cf17b44889fc88

#Fix tests on py33.
PatchScript: perl -pi -e 's/FileExistsError/IsADirectoryError/' testtools/tests/test_testresult.py

Depends: python%type_pkg[python], extras-py%type_pkg[python], mimeparse-py%type_pkg[python]
BuildDepends: fink (>= 0.24.12), setuptools-tng-py%type_pkg[python]

CompileScript: %p/bin/python%type_raw[python] setup.py build

InfoTest: <<
	TestScript: <<
		#!/bin/bash -ev
		# There are failures in test_compat.py
		# with py27 and earlier when run from within fink.
		# It PASSES when run from outside fink.
		# Yeah, I don't get it either.
		if [ %type_pkg[python] -lt 30 ]; then
			make check PYTHON=%p/bin/python%type_raw[python] || exit 1
		else
			make check PYTHON=%p/bin/python%type_raw[python] || exit 2
		fi
	<<
<<

InstallScript: %p/bin/python%type_raw[python] setup.py install --root=%d

DocFiles: LICENSE NEWS README.rst
<<
